doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     '%kernel.cache_dir%/test.db'
                memory:   true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Infrastructure/Entity'
                prefix: 'App\FeeCalculator\Infrastructure\Entity'
                alias: FeeCalculator