parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\FeeCalculator\:
        resource: '../src/'
        exclude:
            - '../src/Domain/*/{Interface,TransferObject}/'
            - '../src/Infrastructure/{Entity}/'
            - '../src/Kernel.php'
    App\FeeCalculator\Fixtures\:
            resource: '../fixtures/'
            tags: [ 'doctrine.fixture.orm' ]
